### ISSUE TITLE
Serial Download Protocol?

### ISSUE THREAD

**Issue by RoganDawes** [usbarmory/crucible#19]
Hi,

I was wondering whether it would make sense to extend crucible to implement support for reading and writing fuses via Serial Download Protocol? That would make it possible to prepare hardware without any OS installed on it at all, as part of the provisioning process.

**Comment by RoganDawes** [comment]
Thanks. I might take a look at implementing this.

**Comment by abarisani** [comment]
We already have a full SDP implementation, check our armory-boot repository.

**Comment by RoganDawes** [comment]
Perfect! Then it should hopefully be a relatively simple matter of gently mixing the two projects together :-) I'll see if I can figure out enough golang to make it work!
