### ISSUE TITLE
Support second MAC address on i.MX7D

### ISSUE THREAD

**Issue by EStrehlau** [usbarmory/crucible#22]
Currently only one MAC address can be access through crucible on i.MX7D.
I.MX7D supports two ethernet controllers, we need to configure/read the MAC address of both through crucible.

This is fixed by: https://github.com/usbarmory/crucible/pull/21.

It would be great if you could do a binary release after merging this PR.

**Comment by abarisani** [comment]
Merged along with a RM [naming consistency fix](https://github.com/usbarmory/crucible/commit/358b5e7adb7f101f870f2b42fe5371460a3cccb6).
