### ISSUE TITLE
invalid go version

### ISSUE THREAD

**Issue by flobro30101** [usbarmory/crucible#29]
crucible/go.mod:3: invalid go version '1.23.1': must match format 1.23

Trying to build on Debian 12, is there a workaround?

**Comment by flobro30101** [comment]
This fix silly... I am not a go person...

diff --git a/go.mod b/go.mod
index fb4fa12..c94ef4a 100644
--- a/go.mod
+++ b/go.mod
@@ -1,6 +1,6 @@
 module github.com/usbarmory/crucible
 
-go 1.23.1
+go 1.23
 
 require (
        cloud.google.com/go/kms v1.20.0

**Comment by abarisani** [comment]
Debian Go version is old and does not support minor version pinning, I suggest you checkout and compile an older version of crucible to work this around, such as [9945c3cef98694b4b5cad63f41edf3ea9056fa12].
