### ISSUE TITLE
IMX8MP nvmem write doesn't work

### ISSUE THREAD

**Issue by Oquirella** [usbarmory/crucible#9]
root@0030D629BD6B:/tmp# dmesg | grep ocotp                                  
[ 4734.504139] imx_ocotp 30350000.ocotp-ctrl: failed write to locked region

root@0030D629BD6B:/tmp# ls -l /sys/bus/nvmem/devices/imx-ocotp0/nvmem  
-rw-r--r-- 1 root root 0 Feb  1 18:48 /sys/bus/nvmem/devices/imx-ocotp0/nvmem

As you can see nvmem write is disabled on the IMX8MP. (release imx_5.4.70_2.3.0)

**Comment by abarisani** [comment]
Which fuses are you trying to write?

**Comment by Oquirella** [comment]
CST_SRK_HASH & CST_SRK_LOCK

**Comment by abarisani** [comment]
Can you please read CST_SRK_LOCK and see if it's set to 1 already?

**Comment by Oquirella** [comment]
I can't write any fuse because /sys/bus/nvmem/devices/imx-ocotp0/nvmem is set read-only on the IMX8MP. (release imx_5.4.70_2.3.0)

**Comment by abarisani** [comment]
The file is not read-only, see the `rw` as first attribute in the listing you provided.

The "failed write to locked region" is a kernel driver message (which proves that you can write to the file, as the drive is being contacted) which highlights that the low level operation failed, usually this happens because the fuse has already been locked.

Please use crucible to *read* fuse CST_SRK_LOCK to confirm its status.

**Comment by Oquirella** [comment]
root@0030D629BF97:/etc/fusemaps# crucible -f /etc/fusemaps -m IMX8MP -r 0 -b 16 -e little  read CST_SRK_LOCK
soc:IMX8MP ref:0 otp:CST_SRK_LOCK op:read addr:0x0 off:9 len:1 val:0x0

**Comment by abarisani** [comment]
The `CST_SRK_HASH` seems written already, is this the value programmed by you?

**Comment by Oquirella** [comment]
xxd  -c 32 -p SRK_1_2_3_4_fuse.bin
07643874d83a90bf8a20ff55aaf089cc4e1f881f1bbab16c2dc5337e7a8cd1db

No, that value doesn't match my SRK binary.

**Comment by abarisani** [comment]
Can you read the entire `OCOTP_LOCK` and paste it here please?

**Comment by Oquirella** [comment]
What is the command to do that?

**Comment by abarisani** [comment]
`crucible -f /etc/fusemaps -m IMX8MP -r 0 -b 16 -e little read OCOTP_LOCK`

**Comment by Oquirella** [comment]
crucible -f /etc/fusemaps -m IMX8MP -r 0 -b 16 -e little read OCOTP_LOCK

soc:IMX8MP ref:0 otp:OCOTP_LOCK op:read addr:0x0 off:0 len:32 val:0xeba9afff

**Comment by abarisani** [comment]
Can you add the `-l` flag for clarity to better read OCOTP_LOCK contents? THanks.

**Comment by Oquirella** [comment]
` 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10 09 08 07 06 05 04 03 02 01 00  OCOTP_LOCK
┏━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┳━━┓ Bank:0 Word:0
┃  ┃  ┃  ┃  ┃  ┃  ┃  ┃  ┃1  0 ┃1  0 ┃  ┃  ┃  ┃  ┃1  0 ┃1  0 ┃  ┃1 ┃1 ┃  ┃  ┃  ┃  ┃  ┃1  1 ┃1  1 ┃ R: 0x00000000
┗━━┻━━┻━━┻━━┻━━┻━━┻━━┻━━╋━━┻━━┻━━┻━━┻━━┻━━┻━━┻━━╋━━┻━━┻━━┻━━┻━━┻━━┻━━┻━━╋━━┻━━┻━━┻━━┻━━┻━━┻━━┻━━┛ W: 0x00000000
                         23 22 ─────────────────────────────────────────────────────────────────  GP2_LOCK
                               21 20 ───────────────────────────────────────────────────────────  GP1_LOCK
                                                 15 14 ─────────────────────────────────────────  MAC_ADDR_LOCK
                                                       13 12 ───────────────────────────────────  USB_ID_LOCK
                                                                10 ─────────────────────────────  SJC_RESP_LOCK
                                                                   09 ──────────────────────────  CST_SRK_LOCK
                                                                                     03 02 ─────  BOOT_CFG_LOCK
                                                                                           01 00  TESTER_LOCK
`

**Comment by abarisani** [comment]
There is a bug with `-l` and `-e little` which we are addressing, the correct display should be with the following:

`crucible -f /etc/fusemaps -m IMX8MP -r 0 -b 16 -l read OCOTP_LOCK`

**Comment by Oquirella** [comment]
![image](https://user-images.githubusercontent.com/67972020/162964810-68292aa0-8e37-4186-8c51-a6f50f36190c.png)

**Comment by abarisani** [comment]
The display bug has been fixed [here](https://github.com/usbarmory/crucible/commit/837bdb65a20de240f92ea57727385352e06b977e)

**Comment by abarisani** [comment]
Apart from the display bug, this board appears to have an SRK already set. There are certain locks in `OCOTP_LOCK` set, which however are not directly linked to the SRK, but the rest of the fuse configuration might have some other values which affect the protection of the `SRK_HASH`. We are not familiar with this board so we cannot provide further comments. We can only say that an SRK was already set and that the kernel driver (not crucible) is preventing you from writing to it.
